global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.19.0.1:9100']
  - job_name: 'recipes-api'
    static_configs:
      - targets: ['host.docker.internal:3007']
    metrics_path: '/api/metrics'