name: monitoring

volumes:
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}

networks:
  monitoring:
    driver: bridge
  loki:
    driver: bridge
services:
  grafana:
    image: grafana/grafana:11.6.2
    container_name: grafana
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - monitoring
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini

  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    restart: on-failure
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=60d"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native_histograms"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - '/:/rootfs:ro'
    command: '--path.rootfs=/host'
    network_mode: host
    pid: host

  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    restart: on-failure
    ports:
      - "3100:3100"
    networks:
      loki:
        aliases:
          - loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml
      - ./loki/tsdb:/data/tsdb
      - ./loki/retention:/data/retention
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: on-failure
    ports:
      - "9080:9080"
    networks:
      - loki
    command:
      - "-config.file=/etc/promtail/config.yml"
    volumes:
      - /var/log:/var/log