name: monitoring

volumes:
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}

networks:
  monitoring:
    driver: bridge
  loki:
    driver: bridge
  monitoring-net:
    external: true

services:
  grafana:
    image: grafana/grafana:11.6.2
    container_name: grafana
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - monitoring
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini

  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    restart: on-failure
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=60d"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
      - "--enable-feature=exemplar-storage"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - '/:/rootfs:ro'
    command: '--path.rootfs=/host'
    network_mode: host
    pid: host

  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    restart: on-failure
    ports:
      - "3100:3100"
    networks:
      loki:
        aliases:
          - loki
      monitoring-net:
        aliases:
          - monitoring-net
    
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml
      - ./loki/tsdb:/data/tsdb
      - ./loki/retention:/data/retention
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: on-failure
    ports:
      - "9080:9080"
    networks:
      - loki
      - monitoring-net
    command:
      - "-config.file=/etc/promtail/config.yml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/promtail/config.yml:/etc/promtail/config.yml 
  
  init-tempo:
    image: &tempoImage grafana/tempo:2.8.0
    user: root
    entrypoint: 
    - "chown"
    - "10001:10001"
    - "/var/tempo"
    volumes:
      - ./tempo_data:/var/tempo
  
  memcached:
    image: memcached:1.6.38
    container_name: memcached
    restart: on-failure
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4
    networks:
      - monitoring

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo_data:/var/tempo
    ports:
      - "4318:4318" 
      - "4317:4317"
    restart: on-failure
    depends_on:
      - init-tempo
      - memcached
    networks:
      - monitoring
      - monitoring-net

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.7
    environment:
      - ENDPOINT=tempo:4317
    restart: always
    depends_on:
      - tempo
    networks:
      - monitoring