apiVersion: v1
kind: Deployment
metadata:
  name: server
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
      tier: frontend
  template:
    metadata:
      labels:
        app: server
        tier: frontend
    spec:
      containers:
      - name: server
        image: nginx:1.27.5
        ports:
        - containerPort: 80
        