apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: server
    tier: replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
      tier: replica
  template:
    metadata:
      name: frontend
      labels:
        app: server
        tier: replica
    spec:
      containers:
      - name: server
        image: nginx:1.27.5
        